#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
if [[ "${TRACE-0}" == "1" ]]; then
    set -o xtrace
fi

main() {
    curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin

    cp ~/.local/kitty.app/share/applications/kitty.desktop ~/.local/share/applications/
    cp ~/.local/kitty.app/share/applications/kitty-open.desktop ~/.local/share/applications/

    sed -i "s|Icon=kitty|Icon=/home/binyomen/.local/kitty.app/share/icons/hicolor/256x256/apps/kitty.png|g" ~/.local/share/applications/kitty*.desktop
    sed -i "s|Exec=kitty|Exec=/home/binyomen/.local/kitty.app/bin/kitty|g" ~/.local/share/applications/kitty*.desktop

    sudo mkdir -p /usr/share/terminfo/x/
    sudo cp ~/.local/kitty.app/share/terminfo/x/xterm-kitty /usr/share/terminfo/x/
}

main "$@"
