#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
if [[ "${TRACE-0}" == "1" ]]; then
    set -o xtrace
fi

main() {
    local -ri percent=$(brightnessctl --machine-readable "$@" | awk -F, '{print $4;}' | sed 's/.$//')
    notify-send \
        --expire-time 1500 \
        --icon sunny \
        --hint string:synchronous:brightness \
        --hint "int:value:$percent" \
        "Brightness  $percent%"
}

main "$@"
