#!/usr/bin/env bash

declare percent=$(brightnessctl -m "$@" | awk -F, '{print $4;}' | sed 's/.$//')
notify-send -i sunny -h string:synchronous:brightness -h int:value:$percent "Brightness  $percent%"
