#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
if [[ "${TRACE-0}" == "1" ]]; then
    set -o xtrace
fi

main() {
    local should_send_notification='false'
    local icon
    local summary
    local body

    local -ri battery_level="$(acpi --battery | grep --perl-regexp --only-matching '[0-9]+(?=%)')"
    local -r battery_status="$(acpi --battery | sed --regexp-extended 's/^Battery [0-9]+: ([^,]+),.+/\1/')"
    if (( "$battery_level" <= 15 )); then
        if [[ "$battery_status" != "Charging" ]]; then
            should_send_notification='true'
            icon='battery-low-symbolic'
            summary='Battery low'
            body="Battery level is $battery_level%!"
        fi
    elif (( "$battery_level" >= 90 )); then
        # "Not charging" means we are plugged in but full on battery.
        if [[ "$battery_status" == 'Charging' || "$battery_status" == 'Not charging' ]]; then
            should_send_notification='true'
            icon='battery-full-symbolic'
            summary='Battery is full'
            body='Unplug charger!'
        fi
    fi

    if [[ "$should_send_notification" == 'true' ]]; then
        notify-send \
            --urgency critical \
            --expire-time 63000 \
            --icon "$icon" \
            --hint string:synchronous:battery-status \
            "$summary" \
            "$body"
    fi
}

main "$@"
