#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
if [[ "${TRACE-0}" == "1" ]]; then
    set -o xtrace
fi

main() {
    polybar-msg cmd quit || echo 'polybar not running'

    echo '---' | tee -a /tmp/polybar.log

    local -r primary_monitor="$(polybar --list-monitors | grep '(primary)$' | cut -d: -f1)"

    for m in $(polybar --list-monitors | cut -d: -f1); do
        if [[ "$m" == "$primary_monitor" ]]; then
            local tray_position='right'
        else
            local tray_position='none'
        fi

        MONITOR="$m" TRAY_POSITION="$tray_position" polybar bar 2>&1 | tee -a /tmp/polybar.log & disown
    done

    echo 'Bars launched…'
}

main "$@"
