#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
if [[ "${TRACE-0}" == "1" ]]; then
    set -o xtrace
fi

main() {
    local -r load="$(cat /proc/loadavg | cut -d' ' -f1)"
    if [[ "$(echo "$load >= $WARN_LOAD" | bc)" == "1" ]]; then
        echo "%{F$ALERT_COLOR}%{T2}%{T-} $load%{F-}"
    else
        echo "%{F$PRIMARY_COLOR}%{T2}%{T-}%{F-} $load"
    fi
}

main "$@"
